# This is a basic workflow to help you get started with Actions

name: download

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  workflow_call:
    secrets:
      PRIVKEY:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      VERSION: 6.1_229

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install deps
        run: |
          sudo apt install wget
          wget https://eclipseclp.org/Distribution/Builds/${VERSION}/x86_64_linux/eclipse_basic.tgz \
               -O eclipse_basic-${VERSION}.tgz
      - name: Commit changes
        run: |
          mkdir .ssh
          echo "${{ secrets.PRIVKEY }}" > .ssh/id_rsa
          ls -la .ssh/id_rsa
          git remote set-url origin git@github.com:vmatare/eclipseclp.git
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add eclipse_basic-${VERSION}.tgz
          git commit -m "Add eclipse_basic-${VERSION}"
          git push
